project:
  type: website
  output-dir: _site

website:
  title: "CS702 Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: labs/week-02.qmd
            text: "Week 2: Decision Theory"

format:
  html:
    theme: cyborg
    toc: true
    code-fold: show
    code-tools: true

execute:
  freeze: auto
