[project]
name = "cs702-lab"
version = "0.1.0"
description = "CS702 Computational Interaction Lab Assignments"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter",
    "pyyaml",
    "numpy",
    "matplotlib",
]
